github:
  clientId: 13e67f9acf45a46a6567
  clientSecret: dc51ddd68a03ff435a497b3023b44a37b55fbc1d
  accessTokenUri: https://github.com/login/oauth/access_token?code={code}&client_id=${github.clientId}&client_secret=${github.clientSecret}
  userUri: https://api.github.com/user?access_token={token}
  authoriseUri: https://github.com/login/oauth/authorize?client_id=${github.clientId}

security:
  basic:
    enabled: false